### PR TITLE
Fix automatically link PR references in monthly changelogs

### LINKED ISSUE #236: Fix changelog to properly link to related PRs
See https://github.com/tscircuit/contribution-tracker/blob/main/changelogs/2025-10.md

Your PR will be closed w/o comment if you do not have proof that your code works! Do not manually modify the markdown!

/bounty $40

### PR DESCRIPTION
**Pull request by RaghavArora14**
## Fix changelog to properly link to related PRs

/Fixes #236
/claim #236
### Changes:
- Add post-processing step to convert # 123 references to [# 123](url) markdown links
- Build PR map from analysis files to lookup PR URLs
- Handle PR number collisions across multiple repositories (store arrays instead of single values)
- Add demo script to showcase the fix without requiring OpenAI API key

### How it works:
1. Parse all PR analysis JSON files and build a lookup map
2. AI generates the changelog with plain #123 references
3. Regex post-processing converts all # 123 → [# 123](url) with actual GitHub URLs

### Testing:
Run `bun run generate:changelog` to see the fix in action using real October 2025 data.

https://github.com/user-attachments/assets/58ccadf4-1215-40e3-a56d-dbeb2be4ad7a

/claim #236
image
image
image

### CODE REVIEW

**Comment by RaghavArora14** [comment]
hey @seveibar can i get a review on this please

File: demo-pr-linking.ts [hunk 1]
```diff
@@ -0,0 +1,156 @@
+/**
```
Comment (ShiboSoftwareDev) [inline demo-pr-linking.ts]: remove this file and share a video of it working

**Comment by ShiboSoftwareDev** [comment]
There shouldn't be a warning of a PR existing in multiple repos, PRs with identical numbers are unique across different repos

**Review by ShiboSoftwareDev — APPROVED** [review]

**Review by seveibar — APPROVED** [review]
