### PR TITLE
fix: special honor to full timers

### LINKED ISSUE #52: Remove the Full timers from the Podium

### PR DESCRIPTION
**Pull request by Ayushjhawar8**
fix #52
image

https://contribution-tracker-ky29ef01g-tscircuit.vercel.app/

### CODE REVIEW

**Review by seveibar — COMMENTED** [review]
This is ok but you should still show the star count and allow the full timers to be clicked etc

**Comment by Ayushjhawar8** [comment]
> This is ok but you should still show the star count and allow the full timers to be clicked etc

Hi, So the full timers are still clickable, and the stars are not there atm for everyone. I added other stats meanwhile for full timers.

**Review by Anshgrover23 — CHANGES_REQUESTED** [review]
@Ayushjhawar8 add the latest screenshots in description.

File: frontend/src/components/ContributorOverview.tsx [hunk 1]
```diff
@@ -9,15 +9,30 @@ import { ContributorCard } from "./ContributorCard"
 import { getAvatarUrl, getProfileUrl } from "../constants/github"
 import { CONTRIBUTION_TYPES, STATS_CONFIG } from "../constants/metrics"
 
+const FULL_TIMERS = ["seveibar", "imrishabh18"]
```
Comment (Anshgrover23) [inline frontend/src/components/ContributorOverview.tsx:12]: can u create a create constant file and add them there as in future if we need to add something we can add more in there.

**Review by Anshgrover23 — CHANGES_REQUESTED** [review]

**Comment by Ayushjhawar8** [comment]
@seveibar @imrishabh18 any updates. please check

**Review by seveibar — APPROVED** [review]
hehe i like it

**Comment by seveibar** [comment]
btw these heads are crushed

image

**Comment by seveibar** [comment]
@Ayushjhawar8 actually, why is it designed like that? The avatar should be on the same line as the name

**Comment by seveibar** [comment]
image

**Comment by Ayushjhawar8** [comment]
@seveibar 
image
is something like this looks good?

**Review by Anshgrover23 — CHANGES_REQUESTED** [review]
@Ayushjhawar8 now the pr no with its icon is not aligned well
image
CC: @seveibar
